DROP TABLE OMS.RVA_CNET CASCADE CONSTRAINTS;

CREATE TABLE OMS.RVA_CNET
(
  EVENT_IDX    INTEGER,
  METER_ID     NUMBER,
  MESSAGE_TX   CHAR(166 BYTE),
  TRANSMITTED  DATE,
  MESSAGE_RX   CHAR(320 BYTE),
  RECEIVED     DATE
);

exit
