DROP TABLE OMS.RVA_WORK CASCADE CONSTRAINTS;

CREATE TABLE OMS.RVA_WORK
(
  EVENT_IDX    INTEGER,
  METER_ID     NUMBER,
  MESSAGE_RX   CHAR(320 BYTE),
  RECEIVED     DATE,
  UTIL_EXTRA_1 CHAR(25),
  UTIL_EXTRA_2 CHAR(25),
  UTIL_EXTRA_3 CHAR(25),
  LAST_PACKET_TIME DATE,
  DEVICE_POWER_STATUS CHAR(2),
  PROCESSED    DATE
);

exit
